#!/bin/bash -e

# 2013-05-13 mza (based on ~/bin/lj)
# updated 2013-12-28
# updated 2014-01-25

declare first="${1}"
shift
for each in ${@}; do
	rest="${rest} | grep -i ${each}"
done
#echo "grep -i \"${first}\" ${file} ${rest}"
#exit 1

cd
cd files-lists
declare files="$(find -maxdepth 1 -iname '*.lf-r' | sort -n)"

for file in ${files}; do
	echo "grepping ${file}..."
	declare string="grep -i \"${first}\" ${file} ${rest}"
	#string="${string} -printf \"%TY-%Tm-%Td+%TH:%TM %12s %p\n\" "
	echo "${string}"
	eval ${string} || /bin/true | sort -n
	echo
done

