#!/bin/bash

declare hostname=$(/bin/hostname)
declare date=$(date +"%Y-%m-%d")
declare filename

function append {
	for each; do
		if [ -e "${each}" ] && [ -r "${each}" ]; then
			tar rf "${filename}" "${each}"
		fi
	done
}

function COPPER_export {
	filename="$HOME/${date}.${hostname}.COPPER-export.key-files.tar"
	cd /tftpboot/copper/root || cd /tftpboot/sl57-export/root
	tar cf "${filename}" \
	        lib/modules/2.6.18/misc \
	        lib/modules/2.6.18/kernel/drivers/net/e100.ko \
	        lib/modules/2.6.18/kernel/drivers/net/e1000e \
	        boot/System.map-2.6.18 \
	        boot/vmlinuz-2.6.18 \
	        usr/local/bin \
	        etc/rc.d/init.d/ttrx \
	        etc/rc.d/init.d/copper \
	        etc/sysconfig/ntpd \
	        etc/ntp.conf \
	        etc/syslog.conf \

	append etc/rc.d/init.d/vme
	append lib/modules/2.6.18/extras
	append lib/modules/2.6.18/build/.config
	append lib/modules/2.6.18/build/drivers/net/Kconfig
	append lib/modules/2.6.18/build/drivers/net/Makefile
	append boot/initrd-2.6.18.img
	append etc/sudoers
	compress
}

function compress {
	if [ -e "${filename}.bz2" ]; then rm "${filename}.bz2"; fi
	bzip2 "${filename}"
	ls -l "${filename}.bz2"
}

#function COPPER_kernel_source {
#tar cjf ~/${date}.COPPER.kernel-source.tar.bz2 \
#	usr/src/kernels/linux-2.6.18/ \
#
#}

function pocketDAQ {
# need to save all custom pxe boot files:
	filename="$HOME/${date}.${hostname}.pocketDAQ.key-files.tar"
	cd /tftpboot
	if [ "$hostname" = "bdaq" ]; then
		tar cf "${filename}" \
			sl57-pxelinux \
			sl57-export/snapshot \

	else
		tar cf "${filename}" \
			linux-install \
			copper/snapshot \
		
	fi

	compress
}

COPPER_export
#COPPER_kernel_source
pocketDAQ

