#!/bin/bash -e

# last updated 2025-01-29 by mza

declare filename="actions-taken-to-clean-up-files.txt"
declare action_file="-exec rm -fv {} ;"
declare action_emptyfile="-exec rm -fv {} ;"
declare action_emptydir="-exec rmdir -v {} ;"
declare -i verbosity=4
declare extracts="extracts"

function find_type_f_iname {
	tarfile="${extracts}/${1}"
	shift
	for spec; do
		echo "${tarfile} ${spec}"
		find -type f -iname "${spec}" -print0 | tar rvf "${tarfile}" --remove-files --null -T - | tee -a ${filename}
	done
}

function find_type_d_iname {
	tarfile="${extracts}/${1}"
	shift
	for spec; do
		echo "${tarfile} ${spec}"
		find -type d -iname "${spec}" -print0 | tar rvf "${tarfile}" --remove-files --null -T - | tee -a ${filename}
	done
}

mkdir -p "${extracts}"

if [ ! -e lf-r.original ]; then
	if [ $verbosity -gt 3 ]; then echo; echo "lf-r.original"; fi
	lf > lf-r.original
fi
if [ ! -e du-ma1.original ]; then
	if [ $verbosity -gt 3 ]; then echo; echo "du-ma1.original"; fi
	dume
	mv du-ma1 du-ma1.original
fi

if [ $verbosity -gt 3 ]; then echo; echo "chmod u+rwx dirs"; fi
find -type d -exec chmod u+rwx --changes {} \; | tee -a ${filename}

if [ $verbosity -gt 3 ]; then echo; echo "sockets"; fi
find -type s -exec rm -v "{}" \; | tee -a ${filename}

if [ $verbosity -gt 3 ]; then echo; echo "links"; fi
find -type l -exec rm -v "{}" \; | tee -a ${filename}

if [ $verbosity -gt 3 ]; then echo; echo "junk dirs and files"; fi
find_type_d_iname junk.tar ".Trash" ".Trash-*"
find_type_f_iname junk.tar "*.pcap" "*.pyc" "*.so" "*.o" "*~" "*.bak" "*.exe.stackdump" ".DS_Store" "desktop.ini"
find_type_f_iname junk.tar "hiberfil.sys" "pagefile.sys"

# "*."
# "*."

if [ $verbosity -gt 3 ]; then echo; echo "superfluous files"; fi
find_type_f_iname language.tar "chinesepod*mp3" "chinesepod*pdf" "chinesepod*mp4"
find_type_f_iname other.tar "*.schbak" "*.sch_bak" "*.symbak" "*.edn" "*.lock" "*.lnk" "*.tmp" "*.dvi" "*.aux" "*.obj" "*.out1" "*.vsd" "*.ll" "*.rep" "*.prm" "*.lst" "ntuser.dat*" "*.txt.gz" "*.hdf5" "*.sys" "*.wdb" "*.itdb" "*.plist" "*.itl" "*.ithmb"
find_type_f_iname data.tar "*rawdata.[0-9][0-9][0-9][0-9][0-9]" "*rawdata.[0-9][0-9][0-9][0-9]" "*.rawdata[0-9][0-9][0-9]" "S*CH[0-9]" "PHD_S*CH[0-9]" "*.fiber[0-9]" "*.root" "*.sroot" "*.rawdata" "*.dat" "*.camac" "ccc[0-9]" "ccc" "aaa" "*.dst" "*.dst[0-9]" "*.datafile" "*.spl" "*.prn" "*.ped"
find_type_f_iname executable.tar "*.dll"
find_type_f_iname installers.tar "*.mui" "*.msi" "*.cab" "*.deb" "*.rpm"
find_type_f_iname log.tar "*.log" "*.jou" "*.status" "VBox.log.*" "VBoxSVC.log.*" "*.out"
find_type_f_iname firmware-build.tar "*.str" "*.ise_ISE_Backup" "*.restore" "*.mgf" "*.dcp" "*.xsvf" "*.svf" "*.xmsgs" "*.xrpt" "*.vdbl" "*.syr" "*.twr" "*.twx" "*.wdb" "*.ngo" "*.vho" "*.mrp" "*.msd" "*.rpx" "*.rpt" "*.rbd" "*.rbb" "*.ngc" "*.ngd" "*.ncd" "*.ngr" "*.ngm" "*.mcs" "*.mcs.gz" "*.bit" "*.bit.gz" "*.hdf" "*.projectmgr" "*.xbcd" "*.xreport" "par_usage_statistics.html" "*.cmd_log" "*.elf" "*.blc" "*.bld" "*.unroutes" "*.par" "*.bgn" "*.map" "*.drc" "*.cdc" "*.xdl" "*.asdb" "*.cgc" "*.cpj" "*.psr" "*.do" "*.glade" "*_flist.txt" "*_readme.txt" "*_pad.txt" "*.ptwx" "*.ut" "*.tsi" "*.cgp" "*.scr" "*.key" "*_xmdf.tcl"
find_type_f_iname geant.tar "*.mac"
find_type_f_iname multiple.tar "*.bin" "*.xml"
find_type_f_iname dotfiles.tar ".gtkrc*" ".kderc*" ".nvidia-settings-rc" ".realplayerrc" ".hxplayerrc" ".dropbox" ".xsession-errors*" ".Xauthority" ".ICEauthority" ".viminfo" ".flexlmrc" ".lesshst" ".recently-used.xbel" ".RapidSVN" ".xscreensaver*" ".xauth*" ".dmrc" ".gtk-bookmarks" ".esd_auth" ".openoffice*" ".rhn-applet.conf" ".mime-types" ".recently-used" "._*"

# occasionally these are useful to include or exclude on a case-by-case basis:
find_type_f_iname executable.tar "*.exe"
find_type_f_iname firmware-build.tar "*.pcf"
find_type_f_iname junk.tar "*.psm"
#find -type f -name "*.pcf" ${action_file} | tee -a ${filename}
#find -type f -name "*.png" ${action_file} | tee -a ${filename} # this line may unintentionally delete useful stuff
#find -type f -name "*.txt" ${action_file} | tee -a ${filename} # this line may unintentionally delete useful stuff, including the file generated by this script...
#find -type f -name "*.csv" ${action_file} | tee -a ${filename} # this line may unintentionally delete useful stuff...
find -type f -wholename "*/coregen/*.pdf" ${action_file} | tee -a ${filename}
find -type f -wholename "*/simulations/*\.raw" ${action_file} | tee -a ${filename}

# these are the to-save files:
#find_type_f_iname tanner.tar "*.spc" "*.vdo" "*.vdb" "*.tdb" "*.tdo" "*.edif" "*.tsdat" "*.tsmeas" "*.tsim" "*.tsdb" "*.wmf"
#find_type_f_iname tanner.tar "*.txt" "*.pdf" "*.pptx" "*.png" "*.xls" # this will grab too much unrelated stuff...

if [ $verbosity -gt 3 ]; then echo; echo "empty files"; fi
find -type f -empty ${action_emptyfile} | tee -a ${filename}

if [ $verbosity -gt 3 ]; then echo; echo "superfluous dirs"; fi
find_type_d_iname language.tar "language" "anki"
find_type_d_iname OS.tar "Windows" "Program Files" "Program Files (x86)" "ProgramData" "Boot" "System Volume Information" "lost+found"
find_type_d_iname executable.tar "MentorGraphics" "PAD_ES_Evaluation" "MSOCache" "teamviewer" "AlmytaSystems" "Anaconda3"
find_type_d_iname dotfiles.tar ".fltk" ".simvision" ".adobe" ".local" ".metadata" ".gconf" ".gnome2" ".gnome2_private" ".evolution" ".Spotlight-V100" ".nx" ".pki" ".vim" ".rhn-applet" ".nautilus" ".gconfd" ".gstreamer*" ".kde" ".swt" ".dbus" ".java" ".ipython" ".fluxbox" ".fonts*" ".fontconfig" ".rootnb" ".config" ".cache" ".pulse"
find_type_d_iname dotfiles.tar ".Xil" ".Xilinx" ".mozilla" ".cpan" ".gegl*" ".texmf-var" ".gimp*" ".gnome" ".opera" ".mcop" ".compiz" ".rhopenoffice*" ".openoffice*" ".icedteaplugin" ".update-notifier" ".irssi" ".qt" ".nbi" ".filezilla" ".putty" ".matlab" ".metacity" ".Skype" ".scim" ".sunpinyin"
find_type_d_iname dotfiles.tar ".SeeVoghRN" ".install4j" ".netx" ".HDI" ".beagle" ".netbeans*" ".thumbnails" ".macromedia" ".Mathematica" ".wine" ".vscode-server" ".vscode" ".eclipse" ".VirtualBox" ".dropbox.cache"
find_type_d_iname dotfiles.tar "*.anydesk" "*.astropy" "*.gitkraken" "*.hplip" "*.jupyter" "*.nano" "*.remmina" "*.virtualenvs"
find_type_d_iname dotfiles.tar ".chipscope" ".eZuceSRN" ".SeeVogh" ".ezwave" ".iscape" ".oracle*"
find_type_d_iname other.tar "isim" "impact_xdb" "iCDB" "Abisuite" "Application Data" "Temporary Internet Files" "Cookies" "Solidworks Downloads" "lowres" "\$Recycle\.Bin"
find_type_d_iname appdata.tar "appdata" # AppData/Thunderbird contains cached emails...
find_type_d_iname junk.tar "Local Settings" 

# occasionally these are useful to include or exclude on a case-by-case basis:
find_type_d_iname svn.tar ".svn" # this line may unintentionally delete useful stuff...
find_type_d_iname git.tar ".git" # this line may unintentionally delete useful stuff...

if [ $verbosity -gt 3 ]; then echo; echo "duplicate files"; fi
echo
lf | duplicate_finder.py
./script_to_remove_all_duplicates_that_are_not_golden.sh

if [ $verbosity -gt 3 ]; then echo; echo "empty dirs"; fi
find -depth -type d -empty ${action_emptydir} | tee -a ${filename}

if [ $verbosity -gt 3 ]; then echo; echo "adjust timestamps of dirs"; fi
adjust_datestamps_of_dirs_based_on_their_contents

if [ $verbosity -gt 3 ]; then echo; echo "lf-r"; fi
lf > lf-r
if [ $verbosity -gt 3 ]; then echo; echo "du-ma1"; fi
dume

