#!/bin/bash -e

configfile="${HOME}/.create-tar-file-with-linux-configuration-stuff-in-etc-rc"
if [ ! -e "${configfile}" ]; then
	echo "
name=\"server-config-files\"
destination=\"/root\"
" >"${configfile}"
fi

. "${configfile}"

date=$(date +"%Y-%m-%d")
#echo ${date}
filename="${destination}/${date}.${name}.tar"
cd /
for each in \
	etc/fstab \
	etc/inittab \
	etc/sudoers \
	etc/sysconfig/networking/devices/ifcfg-em1 \
	etc/sysconfig/networking/devices/ifcfg-eth0 \
	etc/sysconfig/iptables \
	etc/resolv.conf \
	etc/ssh/sshd_config \
	etc/ntp.conf \
	etc/yum.repos.d/ \
	etc/rsyslog.conf \
	etc/logrotate.conf \

do
	#echo "${each}"
	if [ -e "${each}" ]; then
		list="${list} ${each}"
	fi
done

sudo tar cf "${filename}" ${list}
sudo ls -lart "${filename}"

