#!/bin/bash -e

# OS-detecting code suggestions from http://unix.stackexchange.com/questions/6345/how-can-i-get-distribution-name-and-version-number-in-a-simple-shell-script
function detect_OS_ARCH_VER_BITS {
        ARCH=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')
        if [ -f /etc/lsb-release ] && [ $(grep -c ^DISTRIB /etc/lsb-release) -gt 0 ]; then
            . /etc/lsb-release
            OS=$DISTRIB_ID
            VER=$DISTRIB_RELEASE
        elif [ -f /etc/redhat-release ]; then
            STRING=$(cat /etc/redhat-release)
            OS=$(echo $STRING | sed -e "s,^\([^ ]\+\) .*,\1,")
            VER=$(echo $STRING | sed -e "s,.* release \(.*\),\1,")
        elif [ -f /etc/debian_version ]; then
            OS=Debian  # XXX or Ubuntu??
            VER=$(cat /etc/debian_version)
        #elif [ -f /etc/redhat-release ]; then
        else
            OS=$(uname -s)
            VER=$(uname -r)
        fi
        case $(uname -m) in
        x86_64)
            BITS=64
            ;;
        i*86)
            BITS=32
            ;;
        *)
            BITS=?
            ;;
        esac
        case $(uname -m) in
        x86_64)
            ARCH=x64  # or AMD64 or Intel64 or whatever
            ;;
        i*86)
            ARCH=x86  # or IA32 or Intel32 or whatever
            ;;
        *)
            # leave ARCH as-is
            ;;
        esac
	KERNEL=$(uname -r | sed -e "s,^\([2]\.[0-9]\+\.[0-9]\+\).*,\1, ; s,^\([34]\.[0-9]\+\)\..*,\1,")
	KERNEL_RELEASE_DATE=$(grep Released $0 | grep $KERNEL | sed -e "s,.* Released \(.\+\) (.*,(\1)," || echo "")
}

declare OS ARCH VER BITS KERNEL KERNEL_RELEASE_DATE

detect_OS_ARCH_VER_BITS
echo "detected the following:"
echo "        bits=$BITS"
echo "architecture=$ARCH"
echo "          OS=$OS"
echo "     version=$VER"
echo "      kernel=$KERNEL $KERNEL_RELEASE_DATE"
echo

export OS ARCH VER BITS KERNEL KERNEL_RELEASE_DATE

exit 0

# from https://kernelnewbies.org/LinuxVersions?action=raw

= 4.x =
 * ["Linux 4.6"] Released 15 May, 2016 (63 days)
 * ["Linux 4.5"] Released 13 March, 2016 (63 days)
 * ["Linux 4.4"] Released 10 January, 2016 (70 days)
 * ["Linux 4.3"] Released 1 November, 2015 (63 days)
 * ["Linux 4.2"] Released 30 August, 2015 (70 days)
 * ["Linux 4.1"] Released 21 June, 2015 (70 days)
 * ["Linux 4.0"] Released 12 April, 2015 (63 days)

= 3.x =
 * ["Linux 3.19"] Released 8 February, 2015 (63 days)
 * ["Linux 3.18"] Released 7 December, 2014 (63 days)
 * ["Linux 3.17"] Released 5 October, 2014 (63 days)
 * ["Linux 3.16"] Released 3 August, 2014 (56 days)
 * ["Linux 3.15"] Released 8 June, 2014 (70 days)
 * ["Linux 3.14"] Released 30 March, 2014 (70 days)
 * ["Linux 3.13"] Released 19 January, 2014 (78 days)
 * ["Linux 3.12"] Released 2 November, 2013 (61 days)
 * ["Linux 3.11"] Released 2 September, 2013 (64 days)
 * ["Linux 3.10"] Released 30 June, 2013 (63 days)
 * ["Linux 3.9"] Released 28 April, 2013 (69 days)
 * ["Linux 3.8"] Released 18 February, 2013 70 ( days)
 * ["Linux 3.7"] Released 10 December 2012 (71 days)
 * ["Linux 3.6"] Released 30 September, 2012 (71 days)
 * ["Linux 3.5"] Released 21 July, 2012 (62 days)
 * ["Linux 3.4"] Released 20 May, 2012 (63 days)
 * ["Linux 3.3"] Released 18 March, 2012 (74 days)
 * ["Linux 3.2"] Released 4 January, 2012 (72 days)
 * ["Linux 3.1"] Released 24 October, 2011 (95 days)
 * ["Linux 3.0"] Released 21 July, 2011 (64 days)

= 2.6.x =
 * [:Linux 2 6 39:Linux 2.6.39] Released 18 May, 2011 (65 days)
 * [:Linux 2 6 38:Linux 2.6.38] Released 14 March, 2011 (69 days)
 * [:Linux 2 6 37:Linux 2.6.37] Released 4 January, 2011 (76 days)
 * [:Linux 2 6 36:Linux 2.6.36] Released 20 October, 2010 (80 days)
 * [:Linux 2 6 35:Linux 2.6.35] Released 1 August, 2010 (76 days)
 * [:Linux 2 6 34:Linux 2.6.34] Released 16 May, 2010 (81 days)
 * [:Linux 2 6 33:Linux 2.6.33] Released 24 February, 2010 (83 days)
 * [:Linux 2 6 32:Linux 2.6.32] Released 3 December, 2009 (84 days)
 * [:Linux 2 6 31:Linux 2.6.31] Released 9 September, 2009 (92 days)
 * [:Linux 2 6 30:Linux 2.6.30] Released 9 June, 2009 (77 days)
 * [:Linux 2 6 29:Linux 2.6.29] Released 24 March, 2009 (89 days)
 * [:Linux 2 6 28:Linux 2.6.28] Released 25 December, 2008 (77 days)
 * [:Linux 2 6 27:Linux 2.6.27] Released 9 October, 2008 (88 days)
 * [:Linux 2 6 26:Linux 2.6.26] Released 13 July, 2008 (87 days)
 * [:Linux 2 6 25:Linux 2.6.25] Released 17 April, 2008 (84 days)
 * [:Linux 2 6 24:Linux 2.6.24] Released 24 January, 2008 (107 days)
 * [:Linux 2 6 23:Linux 2.6.23] Released 9 October, 2007 (93 days)
 * [:Linux 2 6 22:Linux 2.6.22] Released 8 July, 2007 (73 days)
 * [:Linux 2 6 21:Linux 2.6.21] Released 26 April, 2007 (80 days)
 * [:Linux 2 6 20:Linux 2.6.20] Released 5 February, 2007 (68 days)
 * [:Linux 2 6 19:Linux 2.6.19] Released 29 November, 2006 (70 days)
 * [:Linux 2 6 18:Linux 2.6.18] Released 20 September, 2006 (95 days)
 * [:Linux 2 6 17:Linux 2.6.17] Released 17 June, 2006 (88 days)
 * [:Linux 2 6 16:Linux 2.6.16] Released 20 March, 2006 (76 days)
 * [:Linux 2 6 15:Linux 2.6.15] Released 3 January, 2006 (68 days)
 * [:Linux 2 6 14:Linux 2.6.14] Released 27 October, 2005 (59 days)
 * [:Linux 2 6 13:Linux 2.6.13] Released 29 August, 2005 (73 days)
 * [:Linux 2 6 12:Linux 2.6.12] Released 17 June, 2005 (107 days)
 * [:Linux 2 6 11:Linux 2.6.11] Released 2 March, 2005 (68 days)
 * [:Linux 2 6 10:Linux 2.6.10] Released 24 December, 2004 (66 days)
 * [:Linux 2 6 9:Linux 2.6.9] Released 19 October, 2004 (66 days)
 * [:Linux 2 6 8:Linux 2.6.8] Released 14 August, 2004 (59 days)
 * [:Linux 2 6 7:Linux 2.6.7] Released 16 June, 2004 (37 days)
 * [:Linux 2 6 6:Linux 2.6.6] Released 10 May, 2004 (36 days)
 * [:Linux 2 6 5:Linux 2.6.5] Released 4 April, 2004 (24 days)
 * [:Linux 2 6 4:Linux 2.6.4] Released 11 March, 2004 (22 days)
 * [:Linux 2 6 3:Linux 2.6.3] Released 18 February, 2004 (14 days)
 * [:Linux 2 6 2:Linux 2.6.2] Released 4 February, 2004 (26 days)
 * [:Linux 2 6 1:Linux 2.6.1] Released 9 January, 2004 (22 days)
 * [:Linux 2 6 0:Linux 2.6.0] Released 18 December, 2003

