#!/bin/bash -e

for each; do
	list="${each}.lf-r"
	#if [ -e "${list}" ] && [ "${list}" - "${each}" ]; then
	if [ ! "${list}" -ot "${each}" ]; then
		continue
	fi
	echo "${each}"
	if [ "${each: -3}" = "bz2" ]; then
		extra_options=j
	elif [ "${each: -2}" = "gz" ]; then
		extra_options=z
	else
		extra_options=""
	fi
	tar t${extra_options}f "${each}" --verbose | sed -e "s,[^ ]\+ [^ ]\+ \([ ]\+[0-9]\+\) \([-0-9]\+\) \([:0-9]\+\):[0-9]\+ \(.*\),\2+\3  \1 \4," | sort -n >"${list}"
	#tar t${extra_options}f "${each}" --verbose | sed -e "s,[^ ]\+ [^ ]\+ \([ ]\+[0-9]\+\) \([-0-9]\+\) \([:0-9]\+\):[0-9]\+ \(.*\),\2+\3  \1 \4," | sort -n
	touch "${list}" --reference="${each}"
done

