#!/bin/bash -e

declare file="640" dir="750" # default modes
if [ $# -gt 0 ]; then
	if [ $# -eq 1 ]; then
		file=$1
	elif [ $# -eq 2 ]; then
		file=$1
		dir=$2
	fi
fi
#find -type f -exec chmod --changes $file {} + -o -type d -exec chmod --changes $dir {} +
find -type d -exec chmod --changes $dir {} \; -o -type f -exec chmod --changes $file {} \;

