#!/bin/bash -e

declare TYPE_STRING="-type f"
if [ $# -gt 0 ]; then
	for each; do
		if [ "$1" == "-d" ]; then
			TYPE_STRING="$TYPE_STRING -o -type d"
			shift
		elif [ "$1" == "-l" ]; then
			TYPE_STRING="$TYPE_STRING -o -type l"
			shift
		fi
	done
fi
TYPE_STRING="( $TYPE_STRING )"

# to sort by modification date:
find "${@}" -type d \( -name "proc" -o -name "dev" -o -name "\.svn" -o -name "\.git" \) -prune -o $TYPE_STRING -printf "%TY-%Tm-%Td+%TH:%TM %12s %p\n" | sort -k 1n,1
# a second -k 3 should then sort by filename to break ties, but it doesn't seem to work

