#!/bin/bash -e

# 2013-05-13 mza (based on ~/bin/lj)
# updated 2013-12-28
# updated 2014-01-25
# updated 2016-01-13
# updated 2016-02-23 (rewritten as a single "find | sort | xargs" line)
# updated 2016-06-17 to sort lf-r files by datestamp before grepping them
# updated 2016-06-18 to awk away the non-matching filenames

declare first="${1}"
declare rest=""
shift
for each in "${@}"; do
	rest="${rest} | grep -i ${each}"
done

cd

string="grep -i ${first} \"{}\" ${rest}"
#echo "${string}"

cd "${HOME}/files-lists"
find ./accumulated . -maxdepth 1 -type f -name '*.lf-r' -printf "%TY-%Tm-%Td+%TH:%TM %12s %p\n" | sort -n | colrm 1 30 | xargs -i sh -c "echo \"{}:\"; ${string}" | awk '/^\./ { filename=$0"\n"; } /^[0-9]/ { printf "%s",filename; print $0; filename="" }'

