#!/bin/bash -e

# written 2016-04-28 by mza
# to remedy the fact that svn checkout does not make file datestamps reflect
# the time the file changed...

# format of svn info is:
# Last Changed Date: 2015-01-16 20:56:54 -1000 (Fri, 16 Jan 2015)

# for filenames with "@" in them, svn info will interpret them as revision
# indicators, so the trick is to append @ to every filename to avoid this
# from http://stackoverflow.com/questions/3511348/how-to-remove-a-file-with-in-its-name-from-svn-in-command-line

declare temp=$(mktemp)
if [ $# -gt 0 ]; then
	for each; do
		declare date=$(svn info "$each@" 2>/dev/null | grep "Last Changed Date" | sed -e "s,^Last Changed Date: \(.*\),\1,")
		if [ ! -z "$date" ]; then
			touch --date="$date" $temp
			if [ "$each" -nt $temp ]; then
				echo "changing datestamp of \"$each\" to $date"
				touch --reference=$temp "$each"
			fi
		fi
	done
else
	find -type d -name '.svn' -prune -o -type f -exec $0 {} +
fi
rm $temp

