#!/bin/bash -e

name=$(hostname)
configfile="${HOME}/.update-files-lists-rc"
if [ ! -e "${configfile}" ]; then
	echo "
source=\"${HOME}\"
name=\"${name}\"
destination=\"${HOME}/files-lists\"
accumulation_destination=\"${HOME}/files-lists/accumulated\"
" >"${configfile}"
fi

. "${configfile}"

cd "${source}"
date=$(date +"%Y-%m-%d")
filename_bare="${date}.${name}.lf-r"
filename="${destination}/${filename_bare}"
if [ ! -e "${destination}" ]; then
	mkdir "${destination}"
fi
lf > ${filename} 2>/dev/null

export accumulation_destination
if [ ! -e "${accumulation_destination}" ]; then
	mkdir "${accumulation_destination}"
fi
#cd "${accumulation_destination}"
script="$(dirname $0)/copy-if-not-already-there"
find "${source}/" -type d -wholename "${destination}" -prune -o -type f -name "*.lf-r" -exec ${script} {} +
#find "${source}/" -type f -name "*.lf-r" -exec ${script} {} +

cd "${destination}"
#find -maxdepth 1 -type f -iname "*${name}*" | sort
declare -i count=$(find -maxdepth 1 -type f -iname "*${name}.lf-r" | wc -l)
if [ $count -gt 1 ]; then
	find -maxdepth 1 -type f -iname "20*.${name}.lf-r" -exec mv {} old/ \;
	mv "old/${filename_bare}" .
fi
#echo
find -maxdepth 1 -type f -iname "20*.${name}.lf-r" | sort

