#!/bin/bash -e

dir="${HOME}/yum-history"
mkdir -p "${dir}"
max=$(sudo yum history list | head -n 4 | tail -n 1 | colrm 8)
for i in $(seq 1 $max); do
	i=$(printf %02d $i)
	filename="${dir}/yum-history-info-$i"
	echo "$filename"
	sudo yum history info $i > "$filename"
done

